### ISSUE TITLE
Can we have an integration with Rust Search Extension?

### ISSUE THREAD

**Issue by Folyd** [lukaslueg/macro_railroad_ext#7]
Hi, I'm the author of [Rust Search Extension](https://github.com/huhu/rust-search-extension) and also a faith user of macro_railroad_ext since v0.0.1. I love macro_railroad_ext so much. 

Rust Search Extension is a handy browser plugin that aims to empower every Rustaceans to search docs, crates and etc as quickly as possible. I believe we share the same vision to make the Rust community better. However, the diverse product needs double marketing work to reach more and more Rustaceans. I propose we can have integration between macro_railroad_ext and Rust Search Extension. What do you think? I'll appreciate your suggestion. :)

**Comment by chawyehsu** [comment]
A comment from a RSE user:

I believe you can simply integrate macro_railroad_ext into RSE while keeping the credit, the code is MIT licensed which is compatible with RSE. This extension lacks maintenance for over a year. It can only support docs.rs and the official rust doc site.

If RSE could have the feature of this extension and make it support more rust doc sites like docs.serde.rs, that would be really helpful to Rustaceans.

**Comment by lukaslueg** [comment]
The problem as of now is that `cargo-web` (and its DOM-bindings), which this extension is based on, is unmaintained and fails to even compile since quite a few versions of rustc. So as of today, the extension would require a rewrite based on `wasm-bindgen` (and its DOM-bindings). I never got around to do that, since the underlying `macro_railroad` didn't have significant features added and the extension therefore didn't require a bump.

I may come around to rewrite this thing; if someone wants a go at it, raise your hand :-)

**Comment by Folyd** [comment]
Hi, @lukaslueg. I'd love to rewrite it based on `wasm-bindgen` and integrate it into RSE.

**Comment by lukaslueg** [comment]
@Folyd I'd be delighted to merge such a PR
